(defun farmland (numbers n)
  (cond ((< n 0) "invalid coordinate")
        ((>= n (length numbers)) "invalid coordinate")
        ((= 0 (nth n numbers)) "ineligible")
        ((= 1 (nth n numbers)) "valid")
        ((= 2 (nth n numbers)) "valid")
        ((= 3 (nth n numbers)) "occupied")
        ((= 4 (nth n numbers)) "cannot plant here")
        (t "Fatal error")))
