(defun get-sports (sports times unit)
  (let ((counter 0))
    (dotimes (i (length sports))
      (if (string= unit (aref times i))
          (setf counter (1+ counter))))
    (let ((result (make-array counter)) (currInd 0))
      (dotimes (i (length sports) result)
        (when (string= unit (aref times i))
          (setf (aref result currInd) (aref sports i))
          (setf currInd (1+ currInd)))))))

(defvar SPORTS (make-array 5))
(defvar TIMES (make-array 5))

(defun fill-arrays ()
  (setf (aref SPORTS 0) "Hockey") (setf (aref TIMES 0) "Period")
  (setf (aref SPORTS 1) "Basketball") (setf (aref TIMES 1) "Quarter")
  (setf (aref SPORTS 2) "Soccer") (setf (aref TIMES 2) "Half")
  (setf (aref SPORTS 3) "Football") (setf (aref TIMES 3) "Quarter")
  (setf (aref SPORTS 4) "Tennis") (setf (aref TIMES 4) "Set"))
